spring.application.name=Netflix_Recommendation_Engine
spring.ai.model.embedding=transformers
spring.ai.embedding.transformer.onnx.model-uri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx
spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json